name: Release docker image

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-amd64:
    name: Publish amd64 docker image
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDTAGS: "include_oss include_gcs"
      CGO_ENABLED: 1
      GO111MODULE: "auto"
      GOPATH: ${{ github.workspace }}
      GOOS: linux

    steps:
      - name: Check out source code
        if: ${{ success() }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: ${{ success() }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            VERSION={{ github.ref }}
          tags: ghcr.io/${{ github.repository_owner }}/distribution-amd64/distribution:{{ github.ref }}
  publish-arm64:
    name: Publish arm64 docker image
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDTAGS: "include_oss include_gcs"
      CGO_ENABLED: 1
      GO111MODULE: "auto"
      GOPATH: ${{ github.workspace }}
      GOOS: linux
      GOARCH: arm64

    steps:
      - name: Check out source code
        if: ${{ success() }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: ${{ success() }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          build-args: |
            VERSION={{ github.ref }}
            GOARCH=arm64
          tags: ghcr.io/${{ github.repository_owner }}/distribution-arm64/distribution:{{ github.ref }}
